
[tool.black]
line-length = 120
target-version = ['py36', 'py37', 'py38']
include = '\.pyi?$'
extend-exclude = '''
/(
  # The following are specific to Black, you probably don't want those.
  | external
  | internal
  | migrations
  | node_modules
  | template
  | templates
  | thirdparty
)/
'''
skip-string-normalization = true
quiet = true
